### ISSUE TITLE
Wrong plots in auditory example report

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#206] opened 2016-05-25 14:14 UTC
Some output plots are weird (e.g.: coreg, tsdiffana).

https://circle-artifacts.com/gh/mrahim/pypreprocess/208/artifacts/0/home/ubuntu/nilearn_data/spm_auditory/pypreprocess_output/report_preproc.html

**Comment by dohmatob** [comment] 2016-05-26 19:46
Especially [these](https://circle-artifacts.com/gh/mrahim/pypreprocess/208/artifacts/0/home/ubuntu/nilearn_data/spm_auditory/pypreprocess_output/sub001/reports/report_preproc.html). I just had a quick look, at it seems a step (realign ?) of the preprocessing producess nans in the data.

**Comment by dohmatob** [comment] 2016-05-26 20:09
OK, the problem appears to come from the Realign node.

**Comment by dohmatob** [comment] 2016-05-27 07:29
**Update:** It seems the issue is that SPM produces NaNs, in any case. tsdiffana should do nanmean, nanstd, etc., instead of mean, std, etc. to be robust to this.

**Comment by bthirion** [comment] 2016-05-27 13:00
Regarding the coreg plots, the issue is actually in Nilearn (see issue #1105) and should be handled there. Closing.

**Closed by bthirion** 2016-05-27 13:00 UTC
Labels: Blocker, bug, Build / CI
