### ISSUE TITLE
Non-deterministic test failure in pypreprocess.tests.test_subject_data.test_not_unique_func_filenames_exception_thrown

### ISSUE THREAD

**Issue by lesteve** [neurospin/pypreprocess#267] opened 2017-01-18 09:04 UTC
I have seen it from time to time on Travis and CircleCI. Haven't tried to reproduce locally:

```
======================================================================
ERROR: pypreprocess.tests.test_subject_data.test_not_unique_func_filenames_exception_thrown
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/pypreprocess/pypreprocess/tests/test_subject_data.py", line 79, in test_not_unique_func_filenames_exception_thrown
    sd.sanitize()
  File "/home/ubuntu/pypreprocess/pypreprocess/subject_data.py", line 440, in sanitize
    self._check_func_names_and_shapes()
  File "/home/ubuntu/pypreprocess/pypreprocess/subject_data.py", line 333, in _check_func_names_and_shapes
    if not is_3D(x):
  File "/home/ubuntu/pypreprocess/pypreprocess/io_utils.py", line 264, in is_3D
    image = nibabel.load(image)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/nibabel/loadsave.py", line 40, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
FileNotFoundError: No such file: '/tmp/titi/func/2.img'
```

**Comment by mrahim** [comment] 2017-01-18 09:22
A duplicate of #210

**Closed** 2017-01-18 09:22 UTC
