### ISSUE TITLE
do-report breaks due to an attempt to display a 4D fMRI image

### ISSUE THREAD

**Issue by bthirion** [neurospin/pypreprocess#37] opened 2013-11-19 08:11 UTC
Maybe you shuold coregister also the mean functional image created by realign and use it for display ?
Thanks !

--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    173             else:
    174                 filename = fname
--> 175             __builtin__.execfile(filename, *where)

/volatile/thirion/mygit/mathematicians/do_preprocessing.py in <module>()
     45         do_subject_preproc(preproc_dict, concat=False, do_coreg=True,
     46                            do_stc=False, do_cv_tc=True, do_realign=True,
---> 47                            do_report=True)

/home/bt206016/.local/lib/python2.7/site-packages/pypreprocess/purepython_preproc_utils.pyc in do_subject_preproc(subject_data, verbose, do_caching, do_stc, interleaved, slice_order, do_realign, do_coreg, coreg_func_to_anat, do_cv_tc, fwhm, write_output_images, concat, do_report, parent_results_gallery, shutdown_reloaders)
    297             # generate coreg QA thumbs

    298             subject_data.generate_coregistration_thumbnails(
--> 299                 coreg_func_to_anat=coreg_func_to_anat)
    300 
    301         # garbage collection

/home/bt206016/.local/lib/python2.7/site-packages/pypreprocess/subject_data.pyc in generate_coregistration_thumbnails(self, coreg_func_to_anat, log, comment)
    420             else None,
    421             results_gallery=self.results_gallery,
--> 422             comment=comment
    423             )
    424 

/home/bt206016/.local/lib/python2.7/site-packages/pypreprocess/reporting/preproc_reporter.pyc in generate_coregistration_thumbnails(target, source, output_dir, execution_log_html_filename, results_gallery, comment)
    551         output_dir,
    552         execution_log_html_filename=execution_log_html_filename,
--> 553         results_gallery=results_gallery,
    554         )
    555 

/home/bt206016/.local/lib/python2.7/site-packages/pypreprocess/reporting/preproc_reporter.pyc in generate_registration_thumbnails(target, source, procedure_name, output_dir, execution_log_html_filename, results_gallery)
    417         title="Outline of %s on %s" % (
    418             target[1],
--> 419             source[1],
    420             ))
    421 

/home/bt206016/.local/lib/python2.7/site-packages/joblib-0.6.5-py2.7.egg/joblib/memory.pyc in __call__(self, *args, **kwargs)
    169                           'directory %s'
    170                         % (name, argument_hash, output_dir))
--> 171             return self.call(*args, **kwargs)
    172         else:
    173             try:

/home/bt206016/.local/lib/python2.7/site-packages/joblib-0.6.5-py2.7.egg/joblib/memory.pyc in call(self, *args, **kwargs)
    321         if self._verbose:
    322             print self.format_call(*args, **kwargs)
--> 323         output = self.func(*args, **kwargs)
    324         self._persist_output(output, output_dir)
    325         duration = time.time() - start_time

/home/bt206016/.local/lib/python2.7/site-packages/pypreprocess/reporting/check_preprocessing.pyc in plot_registration(reference_img, coregistered_img, title, cut_coords, slicer, cmap, output_filename)
    249     # plot the coregistered image

    250     if hasattr(coregistered_img, '__len__'):
--> 251         coregistered_img = load_specific_vol(coregistered_img, 0)[0]
    252     # XXX else i'm assuming a nifi object ;)

    253     coregistered_data = coregistered_img.get_data()

/home/bt206016/.local/lib/python2.7/site-packages/pypreprocess/io_utils.pyc in load_specific_vol(vols, t, strict)
     91     if isinstance(vols, list):
     92         n_scans = len(vols)
---> 93         vol = load_vol(vols[t])
     94     elif is_niimg(vols) or isinstance(vols, basestring):
     95         _vols = nibabel.load(vols) if isinstance(vols, basestring) else vols

/home/bt206016/.local/lib/python2.7/site-packages/pypreprocess/io_utils.pyc in load_vol(x)
     66         else:
     67             raise ValueError(
---> 68                 "Each volume must be 3D; got shape %s" % str(vol.shape))
     69     elif len(vol.shape) != 3:
     70             raise ValueError(

ValueError: Each volume must be 3D; got shape (128, 128, 80, 185)

In [2]: %debug
> /home/bt206016/.local/lib/python2.7/site-packages/pypreprocess/io_utils.py(68)load_vol()
     67             raise ValueError(
---> 68                 "Each volume must be 3D; got shape %s" % str(vol.shape))
     69     elif len(vol.shape) != 3:

**Comment by dohmatob** [comment] 2015-03-30 13:12
I can't reproduce this. Do you still observe the bug. Otherwise I'll just close the issue.

**Closed** 2015-04-15 04:13 UTC
